### ISSUE TITLE
Remove Google Services dependency 

### ISSUE THREAD

**Issue by sarvarxyz** [raheemadamboev/todo-app#36]
The project can't be built without the original maintainer's `google-services.json`

**Comment by raheemadamboev** [comment]
You can just remove Firebase dependencies on your project to build or you can create your own Firebase project and integrate it to the project.

Since this is production app, the app needs some Firebase functionality for maintenance purposes.

**Comment by sarvarxyz** [comment]
Okay, you likely don't anticipate any collaborative work on the repository. My point is, by removing the Firebase dependency, other developers could contribute to the core app without needing to set up their own separate Firebase accounts.
